services:
  - type: web
    name: remult-kit-static
    env: static
    repo: https://github.com/jycouet/remult-kit
    branch: main
    buildCommand: npm i -g pnpm; pnpm install --production=false; pnpm -F docs build
    staticPublishPath: ./docs/dist
    buildFilter:
      paths:
        - docs/**
    envVars:
      - key: NODE_VERSION
        value: 22.1.0
    #   - key: TZ
    #     value: utc
